FROM registry.gitlab.com/islandoftex/images/texlive:latest-full

RUN apt-get update -q && apt-get install -qy \
	graphviz \
	python3-pip

#  RUN pip3 install --user \
# 	matplotlib \
# 	seaborn \
# 	pandas \
# 	scikit-learn \
# 	statsmodels
RUN tlmgr install \
	sourceserifpro


ENV HOME /data
WORKDIR /data
