FROM registry.gitlab.com/islandoftex/images/texlive:latest-full

RUN apt-get update -q && apt-get install -qy \
	graphviz \
	python3-matplotlib \
	python3-seaborn \
	python3-pandas \
	python3-sklearn \
	python3-statsmodels

RUN tlmgr install \
	sourceserifpro

RUN wget https://github.com/vslavik/diff-pdf.git
RUN cd diff-pdf; ./bootstrap; ./configure; make; make install

ENV HOME /data
WORKDIR /data
